/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "time.h"


void
timeprog_1(char *host)
{
	CLIENT *clnt;
	ResLogin  *result_1;
	ReqLogin  printime_1_arg;
	printime_1_arg.id = 11;
#ifndef	DEBUG
	clnt = clnt_create (host, TIMEPROG, PRINTIMEVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	//client code
	//调用远程rpc
	result_1 = printime_1(&printime_1_arg, clnt);
	if (result_1 == (ResLogin *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("收到消息 ... %d\n", result_1->result);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	timeprog_1 (host);
exit (0);
}
