/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TIME_H_RPCGEN
#define _TIME_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct ReqLogin {
	int id;
};
typedef struct ReqLogin ReqLogin;

struct ResLogin {
	int result;
};
typedef struct ResLogin ResLogin;

#define TIMEPROG 0x20000001
#define PRINTIMEVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define PRINTIME 1
extern  ResLogin * printime_1(ReqLogin *, CLIENT *);
extern  ResLogin * printime_1_svc(ReqLogin *, struct svc_req *);
extern int timeprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define PRINTIME 1
extern  ResLogin * printime_1();
extern  ResLogin * printime_1_svc();
extern int timeprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_ReqLogin (XDR *, ReqLogin*);
extern  bool_t xdr_ResLogin (XDR *, ResLogin*);

#else /* K&R C */
extern bool_t xdr_ReqLogin ();
extern bool_t xdr_ResLogin ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TIME_H_RPCGEN */
