/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "time.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

ResLogin *
printime_1(ReqLogin *argp, CLIENT *clnt)
{
	static ResLogin clnt_res;

	memset((char *) &clnt_res, 0, sizeof(clnt_res));
	//客户端向服务器端发送调用请求
	if (clnt_call (clnt, PRINTIME,
			(xdrproc_t) xdr_ReqLogin, (caddr_t) argp,
			(xdrproc_t) xdr_ResLogin, (caddr_t) &clnt_res,
			TIMEOUT) != RPC_SUCCESS)
	{
		return (NULL);
	}
	return (&clnt_res);
}
