/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "time.h"

bool_t
xdr_ReqLogin (XDR *xdrs, ReqLogin *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ResLogin (XDR *xdrs, ResLogin *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->result))
		 return FALSE;
	return TRUE;
}
