/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "time.h"

ResLogin *
printime_1_svc(ReqLogin *argp, struct svc_req *rqstp)
{
	static ResLogin  result;

	/*
	 * insert server code here
	 */
	result.result = argp->id;
	return &result;
}
